### PR TITLE
Create Gitea hook service

### LINKED ISSUE #178: Gitea support
Please add support for Gitea.
I have tried to setup Notifico with  my Gitea installation, but all deliveries ends up with error 500. Here are headers:

    Connection: keep-alive
    Content-Length: 3390
    Content-Type: text/html; charset=utf-8
    Date: Sun, 22 Jul 2018 12:27:13 GMT
    Server: nginx/1.10.3 (Ubuntu)
    X-Sentry-Id: 13544b2f9e824afea919610dd1ce1bfc

I can provide as many information as necessary. Just let me know.

### PR DESCRIPTION
**Pull request by sdegrande**
This proposed Gitea hook is based on the code of the GitHub's hook.

Fixes #178

### CODE REVIEW

**Comment by TkTech** [comment]
I'll have time to look at this on Sunday, thanks for the contribution!

**Comment by TkTech** [comment]
I like having the separate service for Gitea, since it may diverge more in the future, but I think we can reduce quite a bit of the duplication unless I'm missing something. Like the form could be a subclass of the Github form, right? Most of the differences are in the payload.

**Comment by sdegrande** [comment]
Thanks for your reply.

The events lists are different (some names are changed, there's at least one additional event and some github events do not exists in gitea). That list could possibly be somehow a parameter of ConfigForm, I guess, but there's also one config option that does not make sense for Gitea. So 2 config 'widgets' are not shared.

There are some 'minor' changes in the payload.

So, yes, most of the code is duplicated. Same goes with gitlab.py, actually, that's why I did not try to factorize the code.

The difference of code between those 3 hooks is sometimes quite "subtle", so factorizing in a base class is perhaps not that easy.

**Comment by TkTech** [comment]
Works for me, thanks again for the contribution. It might take a day or two to deploy, our CI provider doesn't do open source anymore and the deploy tools I used for this project a decade ago don't work anymore 😆 I'll move over to GitHub actions.

**Comment by sdegrande** [comment]
Thanks for the merge, and thanks for your work !

**Comment by sdegrande** [comment]
Hello, @TkTech. Any ETA ?

**Comment by TkTech** [comment]
The host for n.tkte.ch is switching to hetzner, just twiddling my thumb waiting for their support to get it running.

**Comment by TkTech** [comment]
@sdegrande progressing in #207

**Comment by TkTech** [comment]
Deployed, and future deployments are automatic.

**Comment by sdegrande** [comment]
Great ! Thanks a lot.

**Pull request merged**
